'use client';
import { useEffect,useState } from 'react';
import type { StoredEmailRecord } from '../lib/types';
import type { UserProof,UserProofType } from '../lib/user-proof';

export default function AddProofButton({record}:{record:StoredEmailRecord}){
 const[open,setOpen]=useState(false);const[items,setItems]=useState<UserProof[]>([]);const[proofType,setProofType]=useState<UserProofType>('payout');const[summary,setSummary]=useState('');const[amount,setAmount]=useState('');const[currency,setCurrency]=useState('USD');const[reference,setReference]=useState('');const[proofUrl,setProofUrl]=useState('');const[occurredAt,setOccurredAt]=useState('');const[saving,setSaving]=useState(false);const[notice,setNotice]=useState('');
 useEffect(()=>{if(!open)return;void fetch(`/api/user-proof?sender=${encodeURIComponent(record.senderEmail)}`,{cache:'no-store'}).then(r=>r.json()).then(p=>setItems(p.items||[])).catch(()=>{});},[open,record.senderEmail]);
 async function save(){try{setSaving(true);setNotice('Saving proof…');const response=await fetch('/api/user-proof',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({emailRecordId:record.id,senderEmail:record.senderEmail,proofType,proofSummary:summary,amount:amount?Number(amount):null,currency:amount?currency:null,transactionReference:reference||null,proofUrl:proofUrl||null,occurredAt:occurredAt?new Date(occurredAt).toISOString():null})});const payload=await response.json();if(!response.ok)throw new Error(payload.error||'Unable to save proof.');setItems(current=>[payload.item,...current]);setSummary('');setAmount('');setReference('');setProofUrl('');setOccurredAt('');let rechecked=false;if(record.gmailMessageId){const r=await fetch('/api/email-records/reclassify',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({gmailMessageId:record.gmailMessageId})});rechecked=r.ok;}setNotice(rechecked?'Proof saved and this email was rechecked with the new personal evidence. Conflicting security evidence still takes priority.':'Proof saved as personal evidence. It will be used on the next classification/recheck and cannot override conflicting security evidence.');window.dispatchEvent(new Event('inbox-records-updated'));}catch(error){setNotice(error instanceof Error?error.message:'Unable to save proof.');}finally{setSaving(false);}}
 return <div className="analysisBlock"><button type="button" className="copyAction fullWidth" onClick={()=>setOpen(v=>!v)}>＋ Add proof {items.length?`(${items.length})`:''}</button>{open?<div style={{marginTop:12}}><p className="subtle">Add real-world proof such as a payout received, purchase, receipt, account relationship, or identity evidence. Personal proof strengthens context but never overrides failed authentication, sender mismatch, or dangerous links.</p><label>Proof type<select value={proofType} onChange={e=>setProofType(e.target.value as UserProofType)}><option value="payout">Payout / winnings received</option><option value="purchase">Purchase completed</option><option value="receipt">Receipt / transaction</option><option value="account">I have a real account</option><option value="identity">Identity verified independently</option><option value="relationship">Known relationship with sender</option><option value="other">Other proof</option></select></label><label>What does this prove?<textarea value={summary} onChange={e=>setSummary(e.target.value)} placeholder="Example: I withdrew $25 from this account and received it in PayPal on Aug 20."/></label><div className="drawerActions"><label>Amount<input value={amount} onChange={e=>setAmount(e.target.value)} inputMode="decimal" placeholder="25.00"/></label><label>Currency<input value={currency} onChange={e=>setCurrency(e.target.value)} placeholder="USD"/></label></div><label>Transaction/reference number (optional)<input value={reference} onChange={e=>setReference(e.target.value)} /></label><label>Proof link (optional)<input value={proofUrl} onChange={e=>setProofUrl(e.target.value)} placeholder="https://…"/></label><label>Date it happened (optional)<input type="datetime-local" value={occurredAt} onChange={e=>setOccurredAt(e.target.value)}/></label><button type="button" disabled={saving||!summary.trim()} className="safeAction fullWidth" onClick={()=>void save()}>{saving?'Saving…':'Save personal proof'}</button>{notice?<p className="drawerNotice">{notice}</p>:null}{items.length?<div><h4>Saved proof for this sender</h4><ul className="signalList">{items.slice(0,5).map(item=><li key={item.id}><strong>{item.proofType}</strong>: {item.proofSummary}{item.amount!=null?` — ${item.currency||''} ${item.amount}`:''}</li>)}</ul></div>:null}</div>:null}</div>;
}
