import { classifyEmailReliably } from './reliable-classification';
import type { EmailInput } from './types';

type VerificationCase={name:string;expectedCategory:string;expectedSender?:string;email:EmailInput};
const base=(overrides:Partial<EmailInput>):EmailInput=>({sender_email:'sender@example.com',sender_name:'Example Sender',subject:'Hello',body_text:'Hello there.',links:[],known_contact:false,in_reply_thread:false,starred:false,...overrides});
export const classificationVerificationCases:VerificationCase[]=[
{name:'Government impersonation from free email',expectedCategory:'Likely Scam',expectedSender:'Unverified Sender',email:base({sender_email:'justice.notice@gmail.com',body_text:'Department of Justice federal compensation. Act now and send a gift card immediately.'})},
{name:'Authenticated aligned business',expectedCategory:'Verified Business',expectedSender:'Authenticated Domain',email:base({sender_email:'billing@acme-example.com',body_text:'Your receipt is ready.',authentication_results:'spf=pass dkim=pass dmarc=pass',reply_to:'billing@acme-example.com',return_path:'bounce@acme-example.com'})},
{name:'DMARC and DKIM aligned business sender',expectedCategory:'Verified Business',expectedSender:'Authenticated Domain',email:base({sender_email:'billing@aligned-example.com',body_text:'Your account update is ready.',authentication_results:'dkim=pass dmarc=pass',reply_to:'billing@aligned-example.com',return_path:'bounce@aligned-example.com'})},
{name:'Authenticated affiliate opportunity',expectedCategory:'Verified Money Opportunity',expectedSender:'Authenticated Domain',email:base({sender_email:'partners@brand-example.com',body_text:'Join our affiliate program and earn commission on every sale.',authentication_results:'spf=pass dkim=pass dmarc=pass',reply_to:'partners@brand-example.com',return_path:'bounce@brand-example.com'})},
{name:'Authenticated commission payment',expectedCategory:'Verified Money / Payment',expectedSender:'Authenticated Domain',email:base({sender_email:'payments@brand-example.com',body_text:'Your commission payment was sent today.',authentication_results:'spf=pass dkim=pass dmarc=pass',reply_to:'payments@brand-example.com',return_path:'bounce@brand-example.com'})},
{name:'Brand mismatch cannot certify opportunity',expectedCategory:'Opportunity',expectedSender:'Sender Mismatch',email:base({sender_name:'PayPal Partnerships',sender_email:'offers@example.net',body_text:'Affiliate partnership opportunity with commission.',authentication_results:'spf=pass dkim=pass dmarc=pass'})},
{name:'Reply-to mismatch blocks sender certification',expectedCategory:'Money / Payment',expectedSender:'Sender Mismatch',email:base({sender_email:'payments@brand-example.com',reply_to:'claim@different-example.net',body_text:'Your payout was sent.',authentication_results:'spf=pass dkim=pass dmarc=pass'})},
{name:'Partial auth is not certified',expectedCategory:'Opportunity',expectedSender:'Unverified Sender',email:base({sender_email:'partners@brand-example.com',body_text:'Affiliate collaboration opportunity.',authentication_results:'spf=pass dkim=pass'})},
{name:'Previously safe sender becomes trusted sender',expectedCategory:'Verified Opportunity',expectedSender:'Trusted Sender',email:base({sender_email:'partner@trusted-example.com',body_text:'Partnership opportunity for a new referral campaign.',sender_history_decision:'safe'})},
{name:'High-risk payment language remains high risk',expectedCategory:'Needs Review',email:base({sender_email:'billing@vendor-example.com',body_text:'Send bitcoin immediately to this wallet address within 24 hours.'})},
{name:'Subject alone never creates money or opportunity',expectedCategory:'Needs Review',email:base({subject:'Commission payment opportunity',body_text:'Hello. Please see the general information below.'})},
];
export function runClassificationVerification(){const results=classificationVerificationCases.map(test=>{const result=classifyEmailReliably(test.email);const categoryPassed=result.category===test.expectedCategory;const senderPassed=!test.expectedSender||result.sender_verification?.level===test.expectedSender;return{name:test.name,expected:test.expectedCategory,actual:result.category,expectedSender:test.expectedSender||null,actualSender:result.sender_verification?.level||null,risk:result.risk_score,confidence:result.confidence_score,passed:categoryPassed&&senderPassed,reasons:result.reasons};});const passed=results.filter(r=>r.passed).length;return{total:results.length,passed,failed:results.length-passed,passRate:Math.round((passed/results.length)*100),results};}
