import { classifyEmailEvidence } from './classification-engine';
import { findSharedEvidenceMatches } from './shared-scam-evidence';
import type { ClassificationResult, ClassificationRuleMatch, EmailInput, GmailSyncMessage, InboxSummary, MessageType, ReviewState, StoredEmailRecord, TrustLevel } from './types';
const DEFAULT_OWNER_EMAIL='anonymous@local.demo';
type DatabaseEmailRecord={id:string;user_email:string;gmail_message_id:string|null;thread_id:string|null;source:string;sender_name:string|null;sender_email:string;subject:string;body_text:string;category:string;message_type:MessageType|null;trust_level:TrustLevel|null;risk_score:number;confidence_score:number;classification_reasons:string[]|null;matched_rules:ClassificationRuleMatch[]|null;recommended_action:string|null;review_state:ReviewState;reviewed_at:string|null;received_at:string|null;created_at:string;updated_at:string};
type SenderRuleRow={sender_email:string;decision:'safe'|'blocked'};
function getSupabaseCredentials(){const url=process.env.SUPABASE_URL||process.env.NEXT_PUBLIC_SUPABASE_URL;const key=process.env.SUPABASE_SERVICE_ROLE_KEY||process.env.SUPABASE_SECRET_KEY||process.env.SUPABASE_JWT_SECRET;if(!url||!key)throw new Error('Supabase server credentials are not configured.');return{url:url.replace(/\/$/,''),key};}
async function supabaseRequest<T>(path:string,init:RequestInit={}):Promise<T>{const{url,key}=getSupabaseCredentials();const response=await fetch(`${url}/rest/v1/${path}`,{...init,headers:{apikey:key,Authorization:`Bearer ${key}`,'Content-Type':'application/json',...init.headers},cache:'no-store'});const text=await response.text().catch(()=>'');if(!response.ok)throw new Error(`Supabase request failed (${response.status})${text?`: ${text}`:''}`);if(!text.trim())return undefined as T;return JSON.parse(text) as T;}
function mapDatabaseRecord(row:DatabaseEmailRecord):StoredEmailRecord{return{id:row.id,gmailMessageId:row.gmail_message_id,threadId:row.thread_id,source:row.source,senderName:row.sender_name,senderEmail:row.sender_email,subject:row.subject,bodyText:row.body_text,category:row.category,messageType:row.message_type??null,trustLevel:row.trust_level??null,riskScore:row.risk_score,confidenceScore:row.confidence_score,classificationReasons:Array.isArray(row.classification_reasons)?row.classification_reasons:[],matchedRules:Array.isArray(row.matched_rules)?row.matched_rules:[],recommendedAction:row.recommended_action,reviewState:row.review_state,reviewedAt:row.reviewed_at,receivedAt:row.received_at,createdAt:row.created_at,updatedAt:row.updated_at};}
function encodeFilter(v:string){return encodeURIComponent(v);}function domainOf(email:string){return(email.trim().toLowerCase().split('@')[1]||'').trim();}
async function ensureUser(owner:string){await supabaseRequest<unknown>('app_users?on_conflict=email',{method:'POST',headers:{Prefer:'resolution=merge-duplicates,return=minimal'},body:JSON.stringify({email:owner})});}
export async function ensureEmailRecordStore(){getSupabaseCredentials();}
async function getSenderRule(owner:string,sender:string){const rows=await supabaseRequest<SenderRuleRow[]>(`sender_rules?user_email=eq.${encodeFilter(owner)}&sender_email=eq.${encodeFilter(sender.trim().toLowerCase())}&select=sender_email,decision&limit=1`);return rows[0]?.decision??null;}
async function getReviewedDomainHistory(owner:string,domain:string){if(!domain)return null;const rows=await supabaseRequest<Pick<DatabaseEmailRecord,'sender_email'|'review_state'>[]>(`email_records?user_email=eq.${encodeFilter(owner)}&review_state=not.is.null&select=sender_email,review_state&limit=500`);const matching=rows.filter(r=>domainOf(r.sender_email)===domain);return{safe:matching.filter(r=>r.review_state==='safe').length,scam:matching.filter(r=>r.review_state==='scam').length,total:matching.length};}
export async function createEmailRecord(owner:string=DEFAULT_OWNER_EMAIL,email:EmailInput,_result:ClassificationResult){await ensureUser(owner);const[history,domainHistory,communityEvidence]=await Promise.all([getSenderRule(owner,email.sender_email),getReviewedDomainHistory(owner,domainOf(email.sender_email)),findSharedEvidenceMatches(email)]);const result=classifyEmailEvidence({...email,sender_history_decision:history,domain_history:domainHistory,community_evidence:communityEvidence});const reviewState:ReviewState=history==='blocked'?'scam':history==='safe'?'safe':null;const rows=await supabaseRequest<DatabaseEmailRecord[]>('email_records?select=*',{method:'POST',headers:{Prefer:'return=representation'},body:JSON.stringify({user_email:owner,gmail_message_id:null,thread_id:null,source:'manual',sender_name:email.sender_name??null,sender_email:email.sender_email,subject:email.subject,body_text:email.body_text,category:result.category,message_type:result.message_type,trust_level:result.trust_level,risk_score:result.risk_score,confidence_score:result.confidence_score,classification_reasons:result.reasons,matched_rules:result.matched_rules,recommended_action:result.recommended_action,review_state:reviewState,reviewed_at:reviewState?new Date().toISOString():null,received_at:null})});return mapDatabaseRecord(rows[0]);}
export async function upsertSyncedEmailRecords(owner:string=DEFAULT_OWNER_EMAIL,messages:GmailSyncMessage[]){if(!messages.length)return[];await ensureUser(owner);const[senderRules,reviewed]=await Promise.all([supabaseRequest<SenderRuleRow[]>(`sender_rules?user_email=eq.${encodeFilter(owner)}&select=sender_email,decision`),supabaseRequest<Pick<DatabaseEmailRecord,'sender_email'|'review_state'>[]>(`email_records?user_email=eq.${encodeFilter(owner)}&review_state=not.is.null&select=sender_email,review_state&limit=500`)]);const ruleBySender=new Map(senderRules.map(r=>[r.sender_email.trim().toLowerCase(),r.decision]));const domainStats=new Map<string,{safe:number;scam:number;total:number}>();for(const r of reviewed){const d=domainOf(r.sender_email);if(!d)continue;const s=domainStats.get(d)??{safe:0,scam:0,total:0};s.total++;if(r.review_state==='safe')s.safe++;if(r.review_state==='scam')s.scam++;domainStats.set(d,s);}const rows=await Promise.all(messages.map(async message=>{const sender=message.email.sender_email;const history=ruleBySender.get(sender.trim().toLowerCase())??null;const senderDecision:ReviewState=history==='blocked'?'scam':history==='safe'?'safe':null;const communityEvidence=await findSharedEvidenceMatches(message.email);const classification=classifyEmailEvidence({...message.email,sender_history_decision:history,domain_history:domainStats.get(domainOf(sender))??null,community_evidence:communityEvidence});return{user_email:owner,gmail_message_id:message.gmail_message_id,thread_id:message.thread_id??null,source:message.source||'gmail',sender_name:message.email.sender_name??null,sender_email:sender,subject:message.email.subject,body_text:message.email.body_text,category:classification.category,message_type:classification.message_type,trust_level:classification.trust_level,risk_score:classification.risk_score,confidence_score:classification.confidence_score,classification_reasons:classification.reasons,matched_rules:classification.matched_rules,recommended_action:classification.recommended_action,review_state:senderDecision,reviewed_at:senderDecision?new Date().toISOString():null,received_at:message.received_at??null};}));const saved=await supabaseRequest<DatabaseEmailRecord[]>('email_records?on_conflict=user_email,gmail_message_id&select=*',{method:'POST',headers:{Prefer:'resolution=merge-duplicates,return=representation'},body:JSON.stringify(rows)});return saved.map(mapDatabaseRecord);}
export async function updateEmailReview(owner:string=DEFAULT_OWNER_EMAIL,id:string,state:ReviewState){const rows=await supabaseRequest<DatabaseEmailRecord[]>(`email_records?user_email=eq.${encodeFilter(owner)}&id=eq.${encodeFilter(id)}&select=*`,{method:'PATCH',headers:{Prefer:'return=representation'},body:JSON.stringify({review_state:state,reviewed_at:state?new Date().toISOString():null})});return rows[0]?mapDatabaseRecord(rows[0]):null;}
export async function updateSenderReview(owner:string=DEFAULT_OWNER_EMAIL,sender:string,state:Extract<ReviewState,'safe'|'scam'>|null){await ensureUser(owner);const normalized=sender.trim().toLowerCase();if(state)await supabaseRequest<unknown>('sender_rules?on_conflict=user_email,sender_email',{method:'POST',headers:{Prefer:'resolution=merge-duplicates,return=minimal'},body:JSON.stringify({user_email:owner,sender_email:normalized,decision:state==='scam'?'blocked':'safe'})});else await supabaseRequest<unknown>(`sender_rules?user_email=eq.${encodeFilter(owner)}&sender_email=eq.${encodeFilter(normalized)}`,{method:'DELETE',headers:{Prefer:'return=minimal'}});const rows=await supabaseRequest<DatabaseEmailRecord[]>(`email_records?user_email=eq.${encodeFilter(owner)}&sender_email=ilike.${encodeFilter(normalized)}&select=*`,{method:'PATCH',headers:{Prefer:'return=representation'},body:JSON.stringify({review_state:state,reviewed_at:state?new Date().toISOString():null})});return rows.map(mapDatabaseRecord);}
export async function listEmailRecords(owner:string=DEFAULT_OWNER_EMAIL,limit=12){const rows=await supabaseRequest<DatabaseEmailRecord[]>(`email_records?user_email=eq.${encodeFilter(owner)}&select=*&order=received_at.desc.nullslast,created_at.desc&limit=${limit}`);return rows.map(mapDatabaseRecord);}
export async function getInboxSummary(owner:string=DEFAULT_OWNER_EMAIL):Promise<InboxSummary>{const rows=await supabaseRequest<Pick<DatabaseEmailRecord,'category'|'review_state'>[]>(`email_records?user_email=eq.${encodeFilter(owner)}&select=category,review_state`);return{total:rows.length,scams:rows.filter(r=>r.review_state==='scam'||['Scam','Likely Scam'].includes(r.category)).length,opportunities:rows.filter(r=>r.review_state==='opportunity'||r.category==='Opportunity').length,handled:rows.filter(r=>Boolean(r.review_state)).length};}
