export type UserProofType='payout'|'purchase'|'receipt'|'account'|'identity'|'relationship'|'other';
export type UserProof={id:string;emailRecordId:string|null;senderEmail:string;senderDomain:string;proofType:UserProofType;proofSummary:string;amount:number|null;currency:string|null;transactionReference:string|null;proofUrl:string|null;occurredAt:string|null;createdAt:string};
export type NewUserProof={emailRecordId?:string|null;senderEmail:string;proofType:UserProofType;proofSummary:string;amount?:number|null;currency?:string|null;transactionReference?:string|null;proofUrl?:string|null;occurredAt?:string|null};

type Row={id:string;email_record_id:string|null;sender_email:string;sender_domain:string;proof_type:UserProofType;proof_summary:string;amount:number|string|null;currency:string|null;transaction_reference:string|null;proof_url:string|null;occurred_at:string|null;created_at:string};
function credentials(){const url=process.env.SUPABASE_URL||process.env.NEXT_PUBLIC_SUPABASE_URL;const key=process.env.SUPABASE_SERVICE_ROLE_KEY||process.env.SUPABASE_SECRET_KEY||process.env.SUPABASE_JWT_SECRET;if(!url||!key)throw new Error('Supabase server credentials are not configured.');return{url:url.replace(/\/$/,''),key};}
async function request<T>(path:string,init:RequestInit={}):Promise<T>{const{url,key}=credentials();const response=await fetch(`${url}/rest/v1/${path}`,{...init,headers:{apikey:key,Authorization:`Bearer ${key}`,'Content-Type':'application/json',...init.headers},cache:'no-store'});const text=await response.text();if(!response.ok)throw new Error(`User proof store failed (${response.status})${text?`: ${text}`:''}`);return(text?JSON.parse(text):undefined) as T;}
function domainOf(email:string){return(email.trim().toLowerCase().split('@')[1]||'').trim();}
function map(row:Row):UserProof{return{id:row.id,emailRecordId:row.email_record_id,senderEmail:row.sender_email,senderDomain:row.sender_domain,proofType:row.proof_type,proofSummary:row.proof_summary,amount:row.amount==null?null:Number(row.amount),currency:row.currency,transactionReference:row.transaction_reference,proofUrl:row.proof_url,occurredAt:row.occurred_at,createdAt:row.created_at};}
export async function addUserProof(owner:string,input:NewUserProof){const sender=input.senderEmail.trim().toLowerCase();const summary=input.proofSummary.trim();if(!sender||!summary)throw new Error('Sender email and proof summary are required.');const rows=await request<Row[]>('user_proof?select=*',{method:'POST',headers:{Prefer:'return=representation'},body:JSON.stringify({user_email:owner,email_record_id:input.emailRecordId??null,sender_email:sender,sender_domain:domainOf(sender),proof_type:input.proofType,proof_summary:summary,amount:input.amount??null,currency:input.currency?.trim().toUpperCase()||null,transaction_reference:input.transactionReference?.trim()||null,proof_url:input.proofUrl?.trim()||null,occurred_at:input.occurredAt||null})});return map(rows[0]);}
export async function listUserProof(owner:string,senderEmail?:string){const sender=senderEmail?.trim().toLowerCase();const path=sender?`user_proof?user_email=eq.${encodeURIComponent(owner)}&sender_email=eq.${encodeURIComponent(sender)}&select=*&order=created_at.desc`:`user_proof?user_email=eq.${encodeURIComponent(owner)}&select=*&order=created_at.desc&limit=100`;const rows=await request<Row[]>(path);return rows.map(map);}
export async function getUserProofSummary(owner:string,senderEmail:string){const items=await listUserProof(owner,senderEmail);return{count:items.length,payouts:items.filter(x=>x.proofType==='payout').length,purchases:items.filter(x=>x.proofType==='purchase'||x.proofType==='receipt').length,identity:items.filter(x=>x.proofType==='identity'||x.proofType==='relationship').length,latest:items[0]??null};}
